/**
 * Writes public/config.js, which tells the built SPA where the API lives.
 *
 * The URL cannot live in source: it only exists once the API is deployed, and
 * it differs between Render, a branch deploy and localhost. Reading it from the
 * build environment makes pointing the frontend elsewhere a Vercel setting plus
 * a redeploy.
 *
 * On Vercel an unset or malformed value fails the build. A deployment that
 * cannot reach its API is worse than none: it looks healthy, and every sign-in
 * reports a server problem that is really a missing setting.
 */

import { writeFileSync } from 'node:fs';

const TARGET = new URL('../public/config.js', import.meta.url);

const HEADER =
  '// Generated by scripts/write-config.mjs before `npm start` and `npm run build`.\n' +
  '// Do not edit: set FORGE_API_URL in the build environment instead.\n';

// Vercel sets VERCEL=1 in its build environment.
const onVercel = Boolean(process.env.VERCEL);
const raw = (process.env.FORGE_API_URL ?? '').trim();

function fail(message) {
  console.error(`\n[write-config] ${message}\n`);
  process.exit(1);
}

if (!raw) {
  if (onVercel) {
    fail(
      'FORGE_API_URL is not set. In Vercel, open Project > Settings > Environment ' +
        'Variables, add FORGE_API_URL with your Render URL ' +
        '(e.g. https://resumeforge-api.onrender.com), then redeploy.',
    );
  }
  writeFileSync(
    TARGET,
    HEADER + '// FORGE_API_URL is unset, so on localhost the app uses http://localhost:8000/api.\n',
  );
  process.exit(0);
}

let url;
try {
  url = new URL(raw);
} catch {
  fail(`FORGE_API_URL is not a valid URL: ${JSON.stringify(raw)}`);
}

if (url.protocol !== 'https:' && url.protocol !== 'http:') {
  fail(`FORGE_API_URL must start with https:// (got ${url.protocol})`);
}
if (onVercel && url.protocol !== 'https:') {
  // The page is served over https, and browsers block an https page from
  // calling an http API; those requests never reach the server at all.
  fail('FORGE_API_URL must use https:// in a deployed build');
}

// Accept the service root or the /api base, with or without a trailing slash.
let path = url.pathname.replace(/\/+$/, '');
if (!path.endsWith('/api')) path += '/api';
const api = `${url.origin}${path}`;

writeFileSync(TARGET, `${HEADER}window.__FORGE_API__ = ${JSON.stringify(api)};\n`);
console.log(`[write-config] API base: ${api}`);
