"""initial schema

Revision ID: 1b5d927c172e
Revises: 
Create Date: 2026-09-11 12:13:43.647306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b5d927c172e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('base_resumes',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tex_source', sa.Text(), nullable=False),
    sa.Column('template_profile', sa.String(length=40), nullable=False),
    sa.Column('parse_tree', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('compiles', sa.Boolean(), nullable=False),
    sa.Column('parse_warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_resumes_deleted_at'), 'base_resumes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_base_resumes_user_id'), 'base_resumes', ['user_id'], unique=False)
    op.create_index('ix_base_resumes_user_live', 'base_resumes', ['user_id', 'deleted_at'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_deleted_at'), 'job_descriptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('base_resume_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('job_description_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('base_resume_name', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('tex_source', sa.Text(), nullable=False),
    sa.Column('pdf_key', sa.String(length=400), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('change_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gap_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_resume_id'], ['base_resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_deleted_at'), 'generations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generations_status'), 'generations', ['status'], unique=False)
    op.create_index('ix_generations_user_company', 'generations', ['user_id', 'company', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    op.create_index('ix_generations_user_live', 'generations', ['user_id', 'deleted_at'], unique=False)
    op.create_table('generation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_gen_seq', 'generation_events', ['generation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_generation_events_generation_id'), 'generation_events', ['generation_id'], unique=False)
    op.create_table('generation_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('skill', sa.String(length=200), nullable=False),
    sa.Column('normalized_skill', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gaps_user_skill', 'generation_gaps', ['user_id', 'normalized_skill'], unique=False)
    op.create_index(op.f('ix_generation_gaps_generation_id'), 'generation_gaps', ['generation_id'], unique=False)
    op.create_index(op.f('ix_generation_gaps_normalized_skill'), 'generation_gaps', ['normalized_skill'], unique=False)
    op.create_index(op.f('ix_generation_gaps_skill'), 'generation_gaps', ['skill'], unique=False)
    op.create_index(op.f('ix_generation_gaps_user_id'), 'generation_gaps', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('generation_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['state', 'locked_at'], unique=False)
    op.create_index(op.f('ix_jobs_generation_id'), 'jobs', ['generation_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_generation_id'), table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_generation_gaps_user_id'), table_name='generation_gaps')
    op.drop_index(op.f('ix_generation_gaps_skill'), table_name='generation_gaps')
    op.drop_index(op.f('ix_generation_gaps_normalized_skill'), table_name='generation_gaps')
    op.drop_index(op.f('ix_generation_gaps_generation_id'), table_name='generation_gaps')
    op.drop_index('ix_gaps_user_skill', table_name='generation_gaps')
    op.drop_table('generation_gaps')
    op.drop_index(op.f('ix_generation_events_generation_id'), table_name='generation_events')
    op.drop_index('ix_events_gen_seq', table_name='generation_events')
    op.drop_table('generation_events')
    op.drop_index('ix_generations_user_live', table_name='generations')
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_index('ix_generations_user_company', table_name='generations')
    op.drop_index(op.f('ix_generations_status'), table_name='generations')
    op.drop_index(op.f('ix_generations_deleted_at'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_deleted_at'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index('ix_base_resumes_user_live', table_name='base_resumes')
    op.drop_index(op.f('ix_base_resumes_user_id'), table_name='base_resumes')
    op.drop_index(op.f('ix_base_resumes_deleted_at'), table_name='base_resumes')
    op.drop_table('base_resumes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
